### ISSUE TITLE
Enable KVM live migration on local storage

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1284]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5265, https://dev.opennebula.org/issues/5265
Original Date: 2017-07-21

---

None

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Date: 2017-08-31T09:06:47Z

---

This would be a killer feature for us as well.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Date: 2017-08-31T09:07:04Z

---

Strahinja Kustudic wrote:
> This would be a killer feature for us.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Carlo Daffara** (Carlo Daffara)
Original Date: 2017-08-31T10:35:52Z

---

We have simply added "--live" in the parameters of the relevant remote:
remotes/vmm/kvm/migrate

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Strahinja Kustudic** (Strahinja Kustudic)
Original Date: 2017-09-01T13:25:48Z

---

Does it now work just like that? Before I remember you needed to first execute some commands to prepare the destination for migrating, but it was very hard to do right and didn't work all the time.

**Comment by rsmontero** [comment]
fixed

**Comment by kustodian** [comment]
@rsmontero how come this is closed? I can see `--live` being added to the migrate script, but that doesn't actually solve the problem. Live migrations with local storage still fail, so this issues shouldn't be closed.

**Comment by HectorRos** [comment]
I can do easy live migrations with local storage on common virsh installations (without Open Nebula) but not in openNebula.

Do you plan to look at this point again?

**Comment by kustodian** [comment]
@HectorRos what distribution are you using on your hypervisors when you are managing to do live migrations with local storage and how? Every time I try it on Centos 7 it always fails with some strange error.
