### ISSUE TITLE
Segfault when attaching interface to virtual router

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1505]
# Bug Report
## Version of OpenNebula
_Mark the relevant versions affected with [X]_
- [ ] 5.2.2
- [ ] 5.4.0
- [X] 5.4.1 (from ubuntu repo)
- [ ] 5.4.2
- [x] 5.4.3
- [ ] Development build

## Component
- [X] Core
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Sunstone
- [ ] Storage
- [ ] Scheduler
- [ ] vCenter

## Description

OpenNebula die if you try to add new interface to virtual router

OpenNebula version:
```
# oned -v
Copyright 2002-2017, OpenNebula Project, OpenNebula Systems        

OpenNebula 5.4.1 is distributed and licensed for use under the terms of the
Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
****
```
OS version:
```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
Kernel version (both have problem):
```
# uname -a
Linux opennebula 4.4.49-1-pve #1 SMP PVE 4.4.49-86 (Thu, 30 Mar 2017 08:39:20 +0200) x86_64 x86_64 x86_64 GNU/Linux
# uname -a
Linux opennebula 4.13.4-1-pve #1 SMP PVE 4.13.4-25 (Fri, 13 Oct 2017 08:59:53 +0200) x86_64 x86_64 x86_64 GNU/Linux
```

`oned.log`:
```
Wed Nov 22 14:20:00 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 33 -

Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:7776 UID:305 one.vrouter.info invoked , 9
Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:7776 UID:305 one.vrouter.info result SUCCESS, "<VROUTER><ID>9</ID><..."
Wed Nov 22 14:20:00 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 34 -

Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:9488 UID:305 one.vrouter.attachnic invoked , 9, "NIC=[..."
Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:9488 UID:305 one.vrouter.attachnic result SUCCESS, 9
Wed Nov 22 14:20:00 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 35 -

Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:2496 UID:305 one.vnpool.info invoked , -2, -1, -1
Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:2496 UID:305 one.vnpool.info result SUCCESS, "<VNET_POOL><VNET><ID..."
Wed Nov 22 14:20:00 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 36 -

Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:6480 UID:305 one.secgrouppool.info invoked , -2, -1, -1
Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:6480 UID:305 one.secgrouppool.info result SUCCESS, "<SECURITY_GROUP_POOL..."
Wed Nov 22 14:20:00 2017 [Z0][AuM][D]: Message received: AUTHENTICATE SUCCESS 37 -

Wed Nov 22 14:20:00 2017 [Z0][ReM][D]: Req:5808 UID:305 one.vrouter.info invoked , 9
```
`sunstone.log`:
```
Wed Nov 22 14:20:00 2017 [I]: 127.0.0.1 - - [22/Nov/2017:14:20:00 +0100] "POST /vrouter/9/action HTTP/1.0" 204 - 0.0996
Wed Nov 22 14:20:00 2017 [I]: 127.0.0.1 - - [22/Nov/2017:14:20:00 +0100] "GET /vnet?timeout=true&pool_filter=-2&csrftoken=5d1a125071fbe136fadf60dc5f496245 HTTP/1.0" 200 - 0.0458
Wed Nov 22 14:20:00 2017 [I]: 127.0.0.1 - - [22/Nov/2017:14:20:00 +0100] "GET /security_group?timeout=true&pool_filter=-2&csrftoken=5d1a125071fbe136fadf60dc5f496245 HTTP/1.0" 200 - 0.0439
Wed Nov 22 14:20:00 2017 [I]: 127.0.0.1 - - [22/Nov/2017:14:20:00 +0100] "GET /vrouter/9?id=9&csrftoken=5d1a125071fbe136fadf60dc5f496245 HTTP/1.0" 404 - 0.0441
```

`journalctl`:
```
Nov 22 14:13:38 opennebula systemd[1]: opennebula.service: Main process exited, code=exited, status=255/n/a
Nov 22 14:13:38 opennebula systemd[1]: Stopping OpenNebula Cloud Scheduler Daemon...
Nov 22 14:13:38 opennebula systemd[1]: Stopped OpenNebula Cloud Scheduler Daemon.
Nov 22 14:13:38 opennebula systemd[1]: Stopped OpenNebula Cloud Controller Daemon.
Nov 22 14:13:38 opennebula systemd[1]: opennebula.service: Unit entered failed state.
Nov 22 14:13:38 opennebula systemd[1]: opennebula.service: Failed with result 'exit-code'.
```
dmesg
```
[96876.276635] oned[12975]: segfault at 64 ip 0000000000000064 sp 00007fe65a28eea8 error 14 in oned[400000+338000]
```
Same thing if I try to run `oned` manually:
```
# su -s /bin/bash oneadmin -
$ oned -f
$ echo $?
139
```

## How to reproduce
* Download the last [alpine-vrouter (KVM)](https://marketplace.opennebula.systems/appliance/56e156618fb81d0768000001) image from marketplace
* Create new virtual router from it with name `aaa`
* Go to the  `Virtual Routers --> aaa --> Attach NIC`
* Select your network, then click "Attach".

**Comment by kvaps** [comment]
`gdb` debug:

```
$ gdb oned
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from oned...done.
```
```
(gdb) run -f
Starting program: /usr/bin/oned -f
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffeed91700 (LWP 16998)]
[New Thread 0x7fffee590700 (LWP 16999)]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffed761700 (LWP 17017)]
[New Thread 0x7fffecf60700 (LWP 17018)]
[New Thread 0x7fffdffff700 (LWP 17019)]
[New Thread 0x7fffdf7fe700 (LWP 17020)]
[New Thread 0x7fffdeffd700 (LWP 17021)]
[New Thread 0x7fffde7fc700 (LWP 17022)]
[New Thread 0x7fffddffb700 (LWP 17023)]
[New Thread 0x7fffdd7fa700 (LWP 17024)]
[New Thread 0x7fffdcff9700 (LWP 17025)]
[New Thread 0x7fffcbfff700 (LWP 17026)]
[New Thread 0x7fffcb7fe700 (LWP 17027)]
[New Thread 0x7fffcaffd700 (LWP 17028)]
[New Thread 0x7fffca7fc700 (LWP 17029)]
[New Thread 0x7fffc9ffb700 (LWP 17030)]
[New Thread 0x7fffc97fa700 (LWP 17031)]
[New Thread 0x7fffc8ff9700 (LWP 17032)]
[New Thread 0x7fffb7fff700 (LWP 17033)]
[New Thread 0x7fffb77fe700 (LWP 17034)]
[New Thread 0x7fffb6ffd700 (LWP 17225)]
[New Thread 0x7fffb67fc700 (LWP 17226)]
[New Thread 0x7ffff7fd4400 (LWP 17227)]
[Thread 0x7ffff7fd4400 (LWP 17227) exited]
[New Thread 0x7ffff7fd4400 (LWP 17233)]
[Thread 0x7ffff7fd4400 (LWP 17233) exited]
[New Thread 0x7ffff7fd4400 (LWP 17239)]
[Thread 0x7ffff7fd4400 (LWP 17239) exited]
[New Thread 0x7ffff7fd4400 (LWP 17245)]
[New Thread 0x7ffff7fb3400 (LWP 17251)]
[Thread 0x7ffff7fd4400 (LWP 17245) exited]
[New Thread 0x7ffff7fd4400 (LWP 17257)]
[Thread 0x7ffff7fb3400 (LWP 17251) exited]
[Thread 0x7ffff7fd4400 (LWP 17257) exited]
[New Thread 0x7ffff7fb3400 (LWP 17263)]

Thread 30 "oned" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fb3400 (LWP 17263)]
0x000000000052cd3a in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:35
35      src/template/Template.cc: Permission denied.
```
```
(gdb) bt
#0  0x000000000052cd3a in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:35
#1  0x000000000052cdb8 in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:37
#2  0x00000000005f49d7 in VirtualRouter::~VirtualRouter (this=0x7fff8800cf10, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:74
#3  0x00000000005f4a2e in VirtualRouter::~VirtualRouter (this=0x7fff8800cf10, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:75
#4  0x000000000054b5aa in PoolSQL::flush_cache (this=0xa1a100, oid=9) at src/pool/PoolSQL.cc:271
#5  0x000000000054b264 in PoolSQL::get (this=0xa1a100, oid=9, olock=true) at src/pool/PoolSQL.cc:178
#6  0x00000000004ddfda in Request::basic_authorization (pool=0xa1a100, oid=9, op=AuthRequest::USE, auth_object=PoolObjectSQL::VROUTER, att=...) at src/rm/Request.cc:378
#7  0x00000000004ddf39 in Request::basic_authorization (this=0xa3c820, oid=9, op=AuthRequest::USE, att=...) at src/rm/Request.cc:350
#8  0x000000000049fda8 in Request::basic_authorization (this=0xa3c820, oid=9, att=...) at include/Request.h:306
#9  0x000000000049e97e in RequestManagerInfo::request_execute (this=0xa3c820, paramList=..., att=...) at src/rm/RequestManagerInfo.cc:45
#10 0x00000000004dde17 in Request::execute (this=0xa3c820, _paramList=..., _retval=0x7ffff7fb2580) at src/rm/Request.cc:334
#11 0x000000000062f1ad in xmlrpc_c::c_executeMethod (envP=0x7ffff7fb26a0, paramArrayP=0x7fff8802f980, methodPtr=0xa3c820, callInfoPtr=0x7ffff7fb27e0) at registry.cpp:283
#12 0x0000000000633009 in callNamedMethod (resultPP=0x7ffff7fb26d0, callInfoP=0x7ffff7fb27e0, paramArrayP=0x7fff8802f980, methodP=<optimized out>, envP=0x7ffff7fb26a0) at registry.c:307
#13 xmlrpc_dispatchCall (envP=envP@entry=0x7ffff7fb26a0, registryP=registryP@entry=0xa32060, methodName=0x7fff88005200 "one.vrouter.info", paramArrayP=0x7fff8802f980, callInfoP=callInfoP@entry=0x7ffff7fb27e0, 
    resultPP=resultPP@entry=0x7ffff7fb26d0) at registry.c:337
#14 0x000000000063314c in xmlrpc_registry_process_call2 (envP=0x7ffff7fb2760, registryP=0xa32060, 
    callXml=0x7fff880280c0 "<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:D2w8Jpfo6uPaPTOpzPOS7HWX2irSvie/d8frazQ8d8A=</string></value></param><param><"..., 
    callXmlLen=255, callInfo=0x7ffff7fb27e0, responseXmlPP=0x7ffff7fb2758) at registry.c:426
#15 0x000000000062fcd3 in xmlrpc_c::registry::processCall (this=0xa31a78, 
    callXml="<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:D2w8Jpfo6uPaPTOpzPOS7HWX2irSvie/d8frazQ8d8A=</string></value></param><param><"..., 
    callInfoP=0x7ffff7fb27e0, responseXmlP=0x7ffff7fb2890) at registry.cpp:524
#16 0x000000000062dadd in xmlrpc_c::serverAbyss_impl::processCall (this=0x7fff840009c0, 
    call="<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:D2w8Jpfo6uPaPTOpzPOS7HWX2irSvie/d8frazQ8d8A=</string></value></param><param><"..., 
    abyssSessionP=0x7ffff7fb29e0, responseP=0x7ffff7fb2890) at server_abyss.cpp:789
#17 0x000000000062cc6c in xmlrpc_c::processXmlrpcCall (envP=0x7ffff7fb2940, arg=0x7fff840009c0, 
    callXml=0x7fff88011700 "<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:D2w8Jpfo6uPaPTOpzPOS7HWX2irSvie/d8frazQ8d8A=</string></value></param><param><"..., 
    callXmlLen=255, abyssSessionP=0x7ffff7fb29e0, responseXmlPP=0x7ffff7fb2938) at server_abyss.cpp:381
#18 0x000000000063274c in processCall (trace=<optimized out>, accessControl=..., wantChunk=false, xmlProcessorArg=0x7fff840009c0, 
    xmlProcessor=0x62cbbd <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, contentSize=<optimized out>, abyssSessionP=0x7ffff7fb29e0) at abyss_handler.c:392
#19 handleXmlRpcCallReq (requestInfoP=<optimized out>, accessControl=..., wantChunk=<optimized out>, xmlProcessorArg=0x7fff840009c0, 
    xmlProcessor=0x62cbbd <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, abyssSessionP=0x7ffff7fb29e0) at abyss_handler.c:509
#20 xmlrpc_handleIfXmlrpcReq (handlerArg=<optimized out>, abyssSessionP=0x7ffff7fb29e0, handledP=<optimized out>) at abyss_handler.c:573
#21 0x000000000063a500 in runUserHandler (srvP=0x7fff84000a60, sessionP=0x7ffff7fb29e0) at server.c:631
#22 processRequestFromClient (connectionP=connectionP@entry=0x7fff84000d70, lastReqOnConn=lastReqOnConn@entry=false, timeout=<optimized out>, keepAliveP=keepAliveP@entry=0x7ffff7fb2b2c) at server.c:724
#23 0x000000000063a76d in serverFunc (userHandle=0x7fff84000d70) at server.c:796
#24 0x000000000063fcc7 in connJob (userHandle=0x7fff84000d70) at conn.c:39
#25 0x000000000063f547 in execute (arg=0x7fff84001de0) at thread_pthread.c:59
#26 0x00007ffff644c6ba in start_thread (arg=0x7ffff7fb3400) at pthread_create.c:333
#27 0x00007ffff58e13dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by kvaps** [comment]
`gdb` debug:

```
$ gdb oned
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from oned...done.
```
```
(gdb) run -f
Starting program: /usr/bin/oned -f
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffeed91700 (LWP 16998)]
[New Thread 0x7fffee590700 (LWP 16999)]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffed761700 (LWP 17017)]
[New Thread 0x7fffecf60700 (LWP 17018)]
[New Thread 0x7fffdffff700 (LWP 17019)]
[New Thread 0x7fffdf7fe700 (LWP 17020)]
[New Thread 0x7fffdeffd700 (LWP 17021)]
[New Thread 0x7fffde7fc700 (LWP 17022)]
[New Thread 0x7fffddffb700 (LWP 17023)]
[New Thread 0x7fffdd7fa700 (LWP 17024)]
[New Thread 0x7fffdcff9700 (LWP 17025)]
[New Thread 0x7fffcbfff700 (LWP 17026)]
[New Thread 0x7fffcb7fe700 (LWP 17027)]
[New Thread 0x7fffcaffd700 (LWP 17028)]
[New Thread 0x7fffca7fc700 (LWP 17029)]
[New Thread 0x7fffc9ffb700 (LWP 17030)]
[New Thread 0x7fffc97fa700 (LWP 17031)]
[New Thread 0x7fffc8ff9700 (LWP 17032)]
[New Thread 0x7fffb7fff700 (LWP 17033)]
[New Thread 0x7fffb77fe700 (LWP 17034)]
[New Thread 0x7fffb6ffd700 (LWP 17225)]
[New Thread 0x7fffb67fc700 (LWP 17226)]
[New Thread 0x7ffff7fd4400 (LWP 17227)]
[Thread 0x7ffff7fd4400 (LWP 17227) exited]
[New Thread 0x7ffff7fd4400 (LWP 17233)]
[Thread 0x7ffff7fd4400 (LWP 17233) exited]
[New Thread 0x7ffff7fd4400 (LWP 17239)]
[Thread 0x7ffff7fd4400 (LWP 17239) exited]
[New Thread 0x7ffff7fd4400 (LWP 17245)]
[New Thread 0x7ffff7fb3400 (LWP 17251)]
[Thread 0x7ffff7fd4400 (LWP 17245) exited]
[New Thread 0x7ffff7fd4400 (LWP 17257)]
[Thread 0x7ffff7fb3400 (LWP 17251) exited]
[Thread 0x7ffff7fd4400 (LWP 17257) exited]
[New Thread 0x7ffff7fb3400 (LWP 17263)]

Thread 30 "oned" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fb3400 (LWP 17263)]
0x000000000052cd3a in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:35
35      src/template/Template.cc: Permission denied.
```
```
(gdb) bt
#0  0x000000000052cd3a in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:35
#1  0x000000000052cdb8 in Template::~Template (this=0x7fff8801d440, __in_chrg=<optimized out>) at src/template/Template.cc:37
#2  0x00000000005f49d7 in VirtualRouter::~VirtualRouter (this=0x7fff8800cf10, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:74
#3  0x00000000005f4a2e in VirtualRouter::~VirtualRouter (this=0x7fff8800cf10, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:75
#4  0x000000000054b5aa in PoolSQL::flush_cache (this=0xa1a100, oid=9) at src/pool/PoolSQL.cc:271
#5  0x000000000054b264 in PoolSQL::get (this=0xa1a100, oid=9, olock=true) at src/pool/PoolSQL.cc:178
#6  0x00000000004ddfda in Request::basic_authorization (pool=0xa1a100, oid=9, op=AuthRequest::USE, auth_object=PoolObjectSQL::VROUTER, att=...) at src/rm/Request.cc:378
#7  0x00000000004ddf39 in Request::basic_authorization (this=0xa3c820, oid=9, op=AuthRequest::USE, att=...) at src/rm/Request.cc:350
#8  0x000000000049fda8 in Request::basic_authorization (this=0xa3c820, oid=9, att=...) at include/Request.h:306
#9  0x000000000049e97e in RequestManagerInfo::request_execute (this=0xa3c820, paramList=..., att=...) at src/rm/RequestManagerInfo.cc:45
#10 0x00000000004dde17 in Request::execute (this=0xa3c820, _paramList=..., _retval=0x7ffff7fb2580) at src/rm/Request.cc:334
#11 0x000000000062f1ad in xmlrpc_c::c_executeMethod (envP=0x7ffff7fb26a0, paramArrayP=0x7fff8802f980, methodPtr=0xa3c820, callInfoPtr=0x7ffff7fb27e0) at registry.cpp:283
#12 0x0000000000633009 in callNamedMethod (resultPP=0x7ffff7fb26d0, callInfoP=0x7ffff7fb27e0, paramArrayP=0x7fff8802f980, methodP=<optimized out>, envP=0x7ffff7fb26a0) at registry.c:307
#13 xmlrpc_dispatchCall (envP=envP@entry=0x7ffff7fb26a0, registryP=registryP@entry=0xa32060, methodName=0x7fff88005200 "one.vrouter.info", paramArrayP=0x7fff8802f980, callInfoP=callInfoP@entry=0x7ffff7fb27e0, 
    resultPP=resultPP@entry=0x7ffff7fb26d0) at registry.c:337
#14 0x000000000063314c in xmlrpc_registry_process_call2 (envP=0x7ffff7fb2760, registryP=0xa32060, 
    callXml=0x7fff880280c0 "<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=</string></value></param><param><"..., 
    callXmlLen=255, callInfo=0x7ffff7fb27e0, responseXmlPP=0x7ffff7fb2758) at registry.c:426
#15 0x000000000062fcd3 in xmlrpc_c::registry::processCall (this=0xa31a78, 
    callXml="<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=</string></value></param><param><"..., 
    callInfoP=0x7ffff7fb27e0, responseXmlP=0x7ffff7fb2890) at registry.cpp:524
#16 0x000000000062dadd in xmlrpc_c::serverAbyss_impl::processCall (this=0x7fff840009c0, 
    call="<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=</string></value></param><param><"..., 
    abyssSessionP=0x7ffff7fb29e0, responseP=0x7ffff7fb2890) at server_abyss.cpp:789
#17 0x000000000062cc6c in xmlrpc_c::processXmlrpcCall (envP=0x7ffff7fb2940, arg=0x7fff840009c0, 
    callXml=0x7fff88011700 "<?xml version=\"1.0\" ?><methodCall><methodName>one.vrouter.info</methodName><params><param><value><string>serveradmin:kvaps:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=</string></value></param><param><"..., 
    callXmlLen=255, abyssSessionP=0x7ffff7fb29e0, responseXmlPP=0x7ffff7fb2938) at server_abyss.cpp:381
#18 0x000000000063274c in processCall (trace=<optimized out>, accessControl=..., wantChunk=false, xmlProcessorArg=0x7fff840009c0, 
    xmlProcessor=0x62cbbd <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, contentSize=<optimized out>, abyssSessionP=0x7ffff7fb29e0) at abyss_handler.c:392
#19 handleXmlRpcCallReq (requestInfoP=<optimized out>, accessControl=..., wantChunk=<optimized out>, xmlProcessorArg=0x7fff840009c0, 
    xmlProcessor=0x62cbbd <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, abyssSessionP=0x7ffff7fb29e0) at abyss_handler.c:509
#20 xmlrpc_handleIfXmlrpcReq (handlerArg=<optimized out>, abyssSessionP=0x7ffff7fb29e0, handledP=<optimized out>) at abyss_handler.c:573
#21 0x000000000063a500 in runUserHandler (srvP=0x7fff84000a60, sessionP=0x7ffff7fb29e0) at server.c:631
#22 processRequestFromClient (connectionP=connectionP@entry=0x7fff84000d70, lastReqOnConn=lastReqOnConn@entry=false, timeout=<optimized out>, keepAliveP=keepAliveP@entry=0x7ffff7fb2b2c) at server.c:724
#23 0x000000000063a76d in serverFunc (userHandle=0x7fff84000d70) at server.c:796
#24 0x000000000063fcc7 in connJob (userHandle=0x7fff84000d70) at conn.c:39
#25 0x000000000063f547 in execute (arg=0x7fff84001de0) at thread_pthread.c:59
#26 0x00007ffff644c6ba in start_thread (arg=0x7ffff7fb3400) at pthread_create.c:333
#27 0x00007ffff58e13dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by kvaps** [comment]
Also, If I remember well, 5.2 had no this issue

**Comment by juanmont** [comment]
This bug is fixed now, you can apply this patch or update your Opennebula.

[fixed bug](https://github.com/OpenNebula/one/commit/721efccf13484dcccc2802b7ca4f1a92bbcb443e)

**Comment by kvaps** [comment]
Hi @juanmont, seems bug is not fixed. I build oned from source and installed on top of deb-version:
```
$ oned -v
Copyright 2002-2017, OpenNebula Project, OpenNebula Systems        

OpenNebula 5.4.3 is distributed and licensed for use under the terms of the
Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
```
```
Thread 79 "oned" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7f8b400 (LWP 13277)]
0x0000000000527cf0 in Template::~Template (this=0x7fff780b3ce0, __in_chrg=<optimized out>) at src/template/Template.cc:35
35      src/template/Template.cc: Permission denied.
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x0000000000527cf0 in Template::~Template (this=0x7fff780b3ce0, __in_chrg=<optimized out>) at src/template/Template.cc:35
#1  0x0000000000527d6e in Template::~Template (this=0x7fff780b3ce0, __in_chrg=<optimized out>) at src/template/Template.cc:37
#2  0x00000000004f2bca in PoolObjectSQL::~PoolObjectSQL (this=0x7fff78353320, __in_chrg=<optimized out>) at include/PoolObjectSQL.h:139
#3  0x00000000005eb2cb in VirtualRouter::~VirtualRouter (this=0x7fff78353320, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:72
#4  0x00000000005eb300 in VirtualRouter::~VirtualRouter (this=0x7fff78353320, __in_chrg=<optimized out>) at src/vrouter/VirtualRouter.cc:72
#5  0x0000000000545cc0 in PoolSQL::flush_cache (this=0x9b40d0, oid=9) at src/pool/PoolSQL.cc:271
#6  0x000000000054597a in PoolSQL::get (this=0x9b40d0, oid=9, olock=true) at src/pool/PoolSQL.cc:178
#7  0x00000000004d9d34 in Request::basic_authorization (pool=0x9b40d0, oid=9, op=AuthRequest::USE, auth_object=PoolObjectSQL::VROUTER, att=...) at src/rm/Request.cc:378
#8  0x00000000004d9c93 in Request::basic_authorization (this=0x9d4cc0, oid=9, op=AuthRequest::USE, att=...) at src/rm/Request.cc:350
#9  0x000000000049b550 in Request::basic_authorization (this=0x9d4cc0, oid=9, att=...) at include/Request.h:306
#10 0x000000000049a170 in RequestManagerInfo::request_execute (this=0x9d4cc0, paramList=..., att=...) at src/rm/RequestManagerInfo.cc:45
#11 0x00000000004d9b71 in Request::execute (this=0x9d4cc0, _paramList=..., _retval=0x7ffff7f8a5a0) at src/rm/Request.cc:334
#12 0x00007ffff65816c9 in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server++.so.8
#13 0x00007ffff3ed6e39 in xmlrpc_dispatchCall () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server.so.3
#14 0x00007ffff3ed6f88 in xmlrpc_registry_process_call2 () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server.so.3
#15 0x00007ffff6581273 in xmlrpc_c::registry::processCall(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xmlrpc_c::callInfo const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server++.so.8
#16 0x00007ffff6789dd4 in xmlrpc_c::serverAbyss_impl::processCall(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _TSession*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server_abyss++.so.8
#17 0x00007ffff6789ea2 in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server_abyss++.so.8
#18 0x00007ffff42f614a in xmlrpc_handleIfXmlrpcReq () from /usr/lib/x86_64-linux-gnu/libxmlrpc_server_abyss.so.3
#19 0x00007ffff40e74f6 in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_abyss.so.3
#20 0x00007ffff40e77ce in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_abyss.so.3
#21 0x00007ffff40e1da7 in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_abyss.so.3
#22 0x00007ffff40ea9cb in ?? () from /usr/lib/x86_64-linux-gnu/libxmlrpc_abyss.so.3
#23 0x00007ffff63676ba in start_thread (arg=0x7ffff7f8b400) at pthread_create.c:333
#24 0x00007ffff53d33dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by kvaps** [comment]
Hi @juanmont, it's started working after that, but I'm not sure that it's complete solution:

```diff
diff --git a/include/PoolObjectSQL.h b/include/PoolObjectSQL.h
index d5a0caa..ca92848 100644
--- a/include/PoolObjectSQL.h
+++ b/include/PoolObjectSQL.h
@@ -136,7 +136,7 @@ public:

virtual ~PoolObjectSQL()
{
- delete obj_template;
+ //delete obj_template;

pthread_mutex_unlock(&mutex);

diff --git a/src/pool/PoolObjectSQL.cc b/src/pool/PoolObjectSQL.cc
index cce38bf..67583e0 100644
--- a/src/pool/PoolObjectSQL.cc
+++ b/src/pool/PoolObjectSQL.cc
@@ -209,13 +209,13 @@ int PoolObjectSQL::replace_template(
return -1;
}

- delete obj_template;
+ //delete obj_template;

obj_template = new_tmpl;

if (post_update_template(error) == -1)
{
- delete obj_template;
+ //delete obj_template;

if (old_tmpl != 0)
{
@@ -281,7 +281,7 @@ int PoolObjectSQL::append_template(

if (post_update_template(error) == -1)
{
- delete obj_template;
+ //delete obj_template;

if (old_tmpl != 0)
{
```

**Comment by juanmont** [comment]
Hi, we resolved this bug, this is the associated Pull Request: #1516
