### ISSUE TITLE
onedb fsck not count leases from reserverd networks

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#1710]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [ ] 5.4.7
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [x] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [x] Storage & Images
- [ ] Sunstone
- [x] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

I have virtual network with 23, and network reservation for each user from it.

### Expected Behavior

onedb fsck checks network leases in reserved network too.

### Actual Behavior

onedb fsck break network quotas set it to "0":

```
User 350 quotas: VNet 23        LEASES_USED has 1       is      0
User 351 quotas: VNet 23        LEASES_USED has 1       is      0
User 352 quotas: VNet 23        LEASES_USED has 1       is      0
User 353 quotas: VNet 23        LEASES_USED has 1       is      0
User 355 quotas: VNet 23        LEASES_USED has 1       is      0
User 356 quotas: VNet 23        LEASES_USED has 1       is      0
Group 150 quotas: VNet 23       LEASES_USED has 1       is      0
Group 151 quotas: VNet 23       LEASES_USED has 1       is      0
Group 152 quotas: VNet 23       LEASES_USED has 1       is      0
Group 153 quotas: VNet 23       LEASES_USED has 1       is      0
Group 155 quotas: VNet 23       LEASES_USED has 1       is      0
Group 156 quotas: VNet 23       LEASES_USED has 1       is      0
```

## How to reproduce

* Create network reservation
* Run onedb fsck

**Comment by kvaps** [comment]
Issue still there on 5.6.1

**Comment by kvaps** [comment]
Patch for disable this check:

```diff
--- a/usr/lib/one/ruby/onedb/fsck/quotas.rb
+++ b/usr/lib/one/ruby/onedb/fsck/quotas.rb
@@ -273,6 +273,8 @@
             net_quota = doc.root.add_child(doc.create_element("NETWORK_QUOTA"))
         end
 
+        # Disabled due https://github.com/OpenNebula/one/issues/1710
+=begin
         net_quota.xpath("NETWORK").each { |net_elem|
             vnet_id = net_elem.at_xpath("ID").text
 
@@ -297,6 +299,7 @@
             new_elem.add_child(doc.create_element("LEASES")).content = "-1"
             new_elem.add_child(doc.create_element("LEASES_USED")).content = leases_used.to_s
         }
+=end
 
         # Image quotas
 
 ```

**Comment by al3xhh** [comment]
PRs to merge in 5.8 and master:

code: https://github.com/OpenNebula/one/pull/3398
docs: https://github.com/OpenNebula/docs/pull/641

**Comment by atodorov-storpool** [comment]
Just dropping a note that without https://github.com/atodorov-storpool/one/commit/c5601ac6da9259e755102912638fa70bdd8fbd6d
this patch do not count the sizes of the ARs in an AR_POOL. 
It concatenate them instead!
For example if you have 2 ARs with 253 IPs in an AR_POOL, this will update with 253253 instead of 253+253=506

**Comment by al3xhh** [comment]
Thanks @atodorov-storpool I have added it and I have also fixed another bug.

**Comment by kvaps** [comment]
BTW, this patch is not working for me, still see the same:

```
User 2774 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2774 quotas: VNet 2	LEASES_USED has 0 	is	1
User 2775 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2775 quotas: VNet 5	LEASES_USED has 0 	is	1
User 2776 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2776 quotas: VNet 6	LEASES_USED has 0 	is	1
User 2777 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2777 quotas: VNet 7	LEASES_USED has 0 	is	1
User 2778 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2778 quotas: VNet 6	LEASES_USED has 0 	is	1
User 2779 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2779 quotas: VNet 2	LEASES_USED has 0 	is	1
```
and for groups:
```
Group 2571 quotas: VNet 5	LEASES_USED has 0 	is	1
Group 2572 quotas: VNet 23	LEASES_USED has 1 	is	0
Group 2572 quotas: VNet 6	LEASES_USED has 0 	is	1
Group 2573 quotas: VNet 23	LEASES_USED has 1 	is	0
Group 2573 quotas: VNet 7	LEASES_USED has 0 	is	1
Group 2574 quotas: VNet 23	LEASES_USED has 1 	is	0
Group 2574 quotas: VNet 6	LEASES_USED has 0 	is	1
Group 2575 quotas: VNet 23	LEASES_USED has 1 	is	0
Group 2575 quotas: VNet 2	LEASES_USED has 0 	is	1
```

version compiled from `5.8.4`, submitted patch persists in the code

**Comment by kvaps** [comment]
This patch is working https://github.com/OpenNebula/one/commit/b16ea97baef31be50657bced3d02c0d1adec1c1f, this one don't https://github.com/atodorov-storpool/one/commit/c5601ac6da9259e755102912638fa70bdd8fbd6d

**Comment by al3xhh** [comment]
Hello @kvaps tanks for trying it!

Could you please elaborate more about this: `but records them into empty </ID>`, do you mean that the ID of the reserved network is removed?

About this e378cb3 could you please let me know what errors do you get? I have checked and for me it's working, it detects the reserved networks.

**Comment by kvaps** [comment]
@al3xhh eg, I have

```
Group 3133 quotas: VNet 23	LEASES_USED has 6 	is	0
Group 3133 quotas: VNet 111111	LEASES_USED has 0 	is	6
```

but in db:


```sql
(3133,'<QUOTAS><ID>3133</ID><DATASTORE_QUOTA></DATASTORE_QUOTA><NETWORK_QUOTA><NETWORK><ID><![CDATA[23]]></ID><LEASES><![CDATA[6]]></LEASES><LEASES_USED><![CDATA[6]]></LEASES_USED></NETWORK><NETWORK><ID><![CDATA[5432]]></ID><LEASES><![CDATA[-1]]></LEASES><LEASES_USED><![CDATA[5]]></LEASES_USED></NETWORK><NETWORK><ID><![CDATA[5433]]></ID><LEASES><![CDATA[-1]]></LEASES><LEASES_USED><![CDATA[1]]></LEASES_USED></NETWORK><NETWORK><ID><![CDATA[5434]]></ID><LEASES><![CDATA[-1]]></LEASES><LEASES_USED><![CDATA[1]]></LEASES_USED></NETWORK></NETWORK_QUOTA><VM_QUOTA><VM><CPU><![CDATA[0.34]]></CPU><CPU_USED><![CDATA[0.33]]></CPU_USED><MEMORY><![CDATA[2048]]></MEMORY><MEMORY_USED><![CDATA[2048]]></MEMORY_USED><RUNNING_CPU><![CDATA[-1]]></RUNNING_CPU><RUNNING_CPU_USED><![CDATA[0.33]]></RUNNING_CPU_USED><RUNNING_MEMORY><![CDATA[-1]]></RUNNING_MEMORY><RUNNING_MEMORY_USED><![CDATA[2048]]></RUNNING_MEMORY_USED><RUNNING_VMS><![CDATA[-1]]></RUNNING_VMS><RUNNING_VMS_USED><![CDATA[1]]></RUNNING_VMS_USED><SYSTEM_DISK_SIZE><![CDATA[30720]]></SYSTEM_DISK_SIZE><SYSTEM_DISK_SIZE_USED><![CDATA[30720]]></SYSTEM_DISK_SIZE_USED><VMS><![CDATA[1]]></VMS><VMS_USED><![CDATA[1]]></VMS_USED></VM></VM_QUOTA><IMAGE_QUOTA><IMAGE><ID><![CDATA[2054]]></ID><RVMS><![CDATA[-1]]></RVMS><RVMS_USED><![CDATA[1]]></RVMS_USED></IMAGE></IMAGE_QUOTA></QUOTAS>')
```

I have no any network with id `111111`

But I have another record in group_quotas table, where `111111` in LEASES_USED:

```
(807,'<QUOTAS>\n  <ID>807</ID>\n  <DATASTORE_QUOTA/>\n  <NETWORK_QUOTA>\n    <NETWORK>\n      <ID><![CDATA[23]]></ID>\n      <LEASES><![CDATA[6]]></LEASES>\n      <LEASES_USED>6</LEASES_USED>\n    </NETWORK>\n    <NETWORK>\n      <ID><![CDATA[736]]></ID>\n      <LEASES><![CDATA[-1]]></LEASES>\n      <LEASES_USED><![CDATA[6]]></LEASES_USED>\n    </NETWORK>\n    <NETWORK>\n      <ID>313333</ID>\n      <LEASES>-1</LEASES>\n      <LEASES_USED>111111</LEASES_USED>\n    </NETWORK>\n  </NETWORK_QUOTA>\n  <VM_QUOTA>\n    <VM>\n      <CPU><![CDATA[6.01]]></CPU>\n      <CPU_USED><![CDATA[6]]></CPU_USED>\n      <MEMORY><![CDATA[16384]]></MEMORY>\n      <MEMORY_USED><![CDATA[16384]]></MEMORY_USED>\n      <RUNNING_CPU><![CDATA[-1]]></RUNNING_CPU>\n      <RUNNING_CPU_USED>6.00</RUNNING_CPU_USED>\n      <RUNNING_MEMORY><![CDATA[-1]]></RUNNING_MEMORY>\n      <RUNNING_MEMORY_USED>16384</RUNNING_MEMORY_USED>\n      <RUNNING_VMS><![CDATA[-1]]></RUNNING_VMS>\n      <RUNNING_VMS_USED>1</RUNNING_VMS_USED>\n      <SYSTEM_DISK_SIZE><![CDATA[491520]]></SYSTEM_DISK_SIZE>\n      <SYSTEM_DISK_SIZE_USED><![CDATA[491520]]></SYSTEM_DISK_SIZE_USED>\n      <VMS><![CDATA[1]]></VMS>\n      <VMS_USED><![CDATA[1]]></VMS_USED>\n    </VM>\n  </VM_QUOTA>\n  <IMAGE_QUOTA>\n    <IMAGE>\n      <ID><![CDATA[80]]></ID>\n      <RVMS><![CDATA[-1]]></RVMS>\n      <RVMS_USED><![CDATA[1]]></RVMS_USED>\n    </IMAGE>\n  </IMAGE_QUOTA>\n</QUOTAS>')
```

**Comment by kvaps** [comment]
got it, I'll report it in new issue
