### ISSUE TITLE
Import from vCenter

### ISSUE THREAD

**Issue by UAnton** [OpenNebula/one#3057]
**Description**
Import from vCenter 6.7U1 in Sunstone not working.

**To Reproduce**
Import Wild VM from vCenter 6.7U1

**Details**
 - Affected Component: Sunstone
 - Hypervisor: ESXi 6.7
 - Version: 5.8

**Additional context**
Import work from cli but without IP addresses.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment]
Could you provide the log file from OpenNebula and describe the vCenter VM you are trying to import: NICs, Disks and anything else you consider relevant.

Also, you mention that import works from CLI only, if you remove the NIC. Is this correct?

**Comment by UAnton** [comment]
> Also, you mention that import works from CLI only, if you remove the NIC. Is this correct?
No. https://gyazo.com/df3fdc9278351943d2a601ebbe9f3694
After import via CLI, some VMs don't have IP in Sunstone.

**Comment by tinova** [comment]
What error do you get importing from Sunstone?

**Comment by UAnton** [comment]
No errors, only rotating dots.

**Comment by tinova** [comment]
Any error in the developer's console of the browser?

**Comment by UAnton** [comment]
wilds.js:132 Uncaught TypeError: Cannot read property 'DEPLOY_ID' of undefined
    at HTMLInputElement.<anonymous> (wilds.js:132)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at HTMLButtonElement.<anonymous> (wilds.js:130)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.elemData.handle (jquery.js:4549)

**Comment by tinova** [comment]
Fixed in PR #3395

**Comment by UAnton** [comment]
One 5.8.3 - no IP after import. Not fixed.
![9b30563021ef61722ae77e59eef95049](https://user-images.githubusercontent.com/1290580/61576131-8148bc00-aade-11e9-8ba8-f98c97b695ff.png)
